// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"todo-app-go/application/todo"
	"todo-app-go/application/user"
	"todo-app-go/infrastructure/authclient"
	"todo-app-go/infrastructure/database"
	"todo-app-go/infrastructure/database/repository"
	"todo-app-go/interface/handler"
)

// Injectors from container.go:

// UserControllerの依存関係組み立て
func InitializedUserController() (*handler.UserHandler, error) {
	db, err := database.NewGormDB()
	if err != nil {
		return nil, err
	}
	iUserRepository := repository.NewUserRepositoryProvider(db)
	iAuthClient := authclient.NewAuthClient()
	registerUsecase := user.NewRegisterUsecase(iUserRepository, iAuthClient)
	loginUsecase := user.NewLoginUsecase(iUserRepository, iAuthClient)
	userHandler := handler.NewUserHandler(registerUsecase, loginUsecase)
	return userHandler, nil
}

func InitializedTodoController() (*handler.TodoHandler, error) {
	db, err := database.NewGormDB()
	if err != nil {
		return nil, err
	}
	iTodoRepository := repository.NewTodoRepositoryProvider(db)
	createTodoUsecase := todo.NewCreateTodoUsecase(iTodoRepository)
	getTodoUsecase := todo.NewGetTodoUsecase(iTodoRepository)
	getDetailTodoUsecase := todo.NewGetDetailTodoUsecase(iTodoRepository)
	updateTodoUsecase := todo.NewUpdateTodoUsecase(iTodoRepository)
	deleteTodoUsecase := todo.NewDeleteTodoUsecase(iTodoRepository)
	duplicateTodoUsecase := todo.NewDuplicateTodoUsecase(iTodoRepository)
	todoHandler := handler.NewTodoHandler(createTodoUsecase, getTodoUsecase, getDetailTodoUsecase, updateTodoUsecase, deleteTodoUsecase, duplicateTodoUsecase)
	return todoHandler, nil
}
